import turtle
myTurtle = turtle.Turtle()
myTurtle.pencolor('blue')
myTurtle.forward(100)
myTurtle.right(90)
myTurtle.forward(100)
myTurtle.right(90)
myTurtle.forward(100)
myTurtle.right(90)
myTurtle.forward(100)
